version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=kaddem
    volumes:
      - db:/var/lib/mysql

  kaddem:
    image: zeinebmaatalli/kaddem
    container_name: kaddem
    ports:
      - "8089:8089"
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/kaddem?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
     restart: unless-stopped
     
  front-equipe:
    image: zeinebmaatalli/front-equipe
    container_name: front-equipe
    ports:
      - "8083:8083"
    depends_on:
      - kaddem
    

volumes:
  db:
