# Étape 1 : build Angular app
FROM node:18-alpine as build
WORKDIR /app
COPY . .
RUN npm install && npm run build --prod

# Étape 2 : servir avec nginx
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 83
CMD ["nginx", "-g", "daemon off;"]
